#!/bin/sh

sxhkd &
picom &
nitrogen --restore &
# xfce4-panel &
~/.config/polybar/launch.sh &
dropbox &

bspc monitor DVI-D-0			-d 1 2 3
bspc monitor HDMI-0			-d 4 5 6

bspc config border_width         	0
# bspc config focused_border_color \#D8DEE9
bspc config window_gap          	25

bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	false
bspc config split_ratio          	0.6
bspc config borderless_monocle   	true
bspc config gapless_monocle     	false
